[[plugins]]
repo = 'neovim/nvim-lspconfig'

hook_add = '''
lua << EOF
    require('nvim-lspconfig')
EOF
'''

[[plugins]]
repo = 'williamboman/mason.nvim'

hook_add = '''
lua << EOF
    require('mason-lsp')
EOF
'''

[[plugins]]
repo = 'williamboman/mason-lspconfig.nvim'

[[plugins]]
repo = 'Shatur/neovim-ayu'

[[plugins]]
repo = 'lambdalisue/fern.vim'

[[plugins]]
repo = 'nvim-lua/completion-nvim'

[[plugins]]
repo = 'cohama/lexima.vim'

